### ISSUE TITLE
Not even t3 stack

### ISSUE THREAD

**Issue by bdsqqq** [tonyaellie/t3gay#1]
How pride-related can this be if the repo isn't even proudly using the t3 stack?? smh

**Comment by tonyaellie** [comment]
i wanna be edgy tho :(

**Comment by bdsqqq** [comment]
You're so close(not an edging joke) to doing it tho, just `pnpm create t3-app`, I believe in you

**Comment by tonyaellie** [comment]
![fftpr.png](https://github.com/tonyaellie/t3gay/assets/46281725/de8c45b1-8026-47de-9426-019e400a0344)

**Comment by tonyaellie** [comment]
just for you i did it <3

**Comment by bdsqqq** [comment]
best maintainer ever 🫡
